server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booker
    username: booker
    password: booker
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate.SQL: debug